/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_urlwhitelist_2eproto__INCLUDED
#define PROTOBUF_C_urlwhitelist_2eproto__INCLUDED

#include "protobuf-c.h"

PROTOBUF_C_BEGIN_DECLS


typedef struct _URLWhitelist URLWhitelist;


/* --- enums --- */


/* --- messages --- */

struct  _URLWhitelist
{
  ProtobufCMessage base;
  size_t n_url;
  char **url;
};
#define URLWHITELIST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&urlwhitelist__descriptor) \
    , 0,NULL }


/* URLWhitelist methods */
void   urlwhitelist__init
                     (URLWhitelist         *message);
size_t urlwhitelist__get_packed_size
                     (const URLWhitelist   *message);
size_t urlwhitelist__pack
                     (const URLWhitelist   *message,
                      uint8_t             *out);
size_t urlwhitelist__pack_to_buffer
                     (const URLWhitelist   *message,
                      ProtobufCBuffer     *buffer);
URLWhitelist *
       urlwhitelist__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   urlwhitelist__free_unpacked
                     (URLWhitelist *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*URLWhitelist_Closure)
                 (const URLWhitelist *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor urlwhitelist__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_urlwhitelist_2eproto__INCLUDED */
