/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_guest_5fmode_2eproto__INCLUDED
#define PROTOBUF_C_guest_5fmode_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _Subnet Subnet;
typedef struct _GuestModeRules GuestModeRules;


/* --- enums --- */


/* --- messages --- */

struct  _Subnet
{
  ProtobufCMessage base;
  uint32_t ip;
  uint32_t mask;
};
#define SUBNET__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&subnet__descriptor) \
    , 0, 0 }


struct  _GuestModeRules
{
  ProtobufCMessage base;
  size_t n_ifnames;
  char **ifnames;
  size_t n_ports;
  uint32_t *ports;
  size_t n_snets;
  Subnet **snets;
};
#define GUEST_MODE_RULES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&guest_mode_rules__descriptor) \
    , 0,NULL, 0,NULL, 0,NULL }


/* Subnet methods */
void   subnet__init
                     (Subnet         *message);
size_t subnet__get_packed_size
                     (const Subnet   *message);
size_t subnet__pack
                     (const Subnet   *message,
                      uint8_t             *out);
size_t subnet__pack_to_buffer
                     (const Subnet   *message,
                      ProtobufCBuffer     *buffer);
Subnet *
       subnet__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   subnet__free_unpacked
                     (Subnet *message,
                      ProtobufCAllocator *allocator);
/* GuestModeRules methods */
void   guest_mode_rules__init
                     (GuestModeRules         *message);
size_t guest_mode_rules__get_packed_size
                     (const GuestModeRules   *message);
size_t guest_mode_rules__pack
                     (const GuestModeRules   *message,
                      uint8_t             *out);
size_t guest_mode_rules__pack_to_buffer
                     (const GuestModeRules   *message,
                      ProtobufCBuffer     *buffer);
GuestModeRules *
       guest_mode_rules__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   guest_mode_rules__free_unpacked
                     (GuestModeRules *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Subnet_Closure)
                 (const Subnet *message,
                  void *closure_data);
typedef void (*GuestModeRules_Closure)
                 (const GuestModeRules *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor subnet__descriptor;
extern const ProtobufCMessageDescriptor guest_mode_rules__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_guest_5fmode_2eproto__INCLUDED */
