/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "urllist.pb-c.h"
void   urllist__init
                     (URLList         *message)
{
  static URLList init_value = URLLIST__INIT;
  *message = init_value;
}
size_t urllist__get_packed_size
                     (const URLList *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &urllist__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t urllist__pack
                     (const URLList *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &urllist__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t urllist__pack_to_buffer
                     (const URLList *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &urllist__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
URLList *
       urllist__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (URLList *)
     protobuf_c_message_unpack (&urllist__descriptor,
                                allocator, len, data);
}
void   urllist__free_unpacked
                     (URLList *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &urllist__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor urllist__field_descriptors[1] =
{
  {
    "url",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    PROTOBUF_C_OFFSETOF(URLList, n_url),
    PROTOBUF_C_OFFSETOF(URLList, url),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned urllist__field_indices_by_name[] = {
  0,   /* field[0] = url */
};
static const ProtobufCIntRange urllist__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor urllist__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "URLList",
  "URLList",
  "URLList",
  "",
  sizeof(URLList),
  1,
  urllist__field_descriptors,
  urllist__field_indices_by_name,
  1,  urllist__number_ranges,
  (ProtobufCMessageInit) urllist__init,
  NULL,NULL,NULL    /* reserved[123] */
};
